/* mod_effects.c - the Adjustments and Effects menus (MENUS.md, lane F):
 * one command per registered effect ("adjust.<id>", "effects.<id>"),
 * Effects > Repeat (Ctrl+F, Effects menu items only, with their last
 * parameters), Effects > Plugin Errors..., the plugin folders scanned at
 * startup and the Curves and Levels editors. The menus themselves are
 * generated by menu.c from the registry's menu paths (submenus and items in
 * alphabetical order). The engine (sessions, dialogs, preview, commit,
 * plugin loader) lives in src/app/fx; see afx.h and docs/app/EFFECTS.md.
 *
 * Plugin folders (ADR-008 OD-9): PAL_DIR_DATA/plugins (per user) and a
 * portable "plugins" folder next to the executable. Runs without a
 * settings folder (tests and scripted runs, config_dir "") skip the per-
 * user folder so they never depend on what the user installed;
 * --disable-plugins skips both (K-CLI-NOPLUGINS). Main thread. */
#include "../app_internal.h"
#include "fx/afx.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ---- commands ------------------------------------------------------------------------ */
static void cmd_effect(app *a, const app_cmd *c)
{
    const fx_effect *fx = (const fx_effect *)c->ud;
    if (fx) (void)afx_open(a, fx);
}

static bool can_repeat(app *a, const app_cmd *c)
{
    (void)c;
    return afx_can_repeat(a);
}

static void cmd_repeat(app *a, const app_cmd *c)
{
    (void)c;
    (void)afx_repeat(a);
}

static bool has_plugin_errors(app *a, const app_cmd *c)
{
    (void)c;
    return afx_plugins_error_count(afx_app_plugins(a)) > 0u;
}

static void cmd_plugin_errors(app *a, const app_cmd *c)
{
    (void)c;
    afx_plugin_errors_dialog(a);
}

void afx_register_commands(app *a)
{
    uint32_t n = a->fx ? fx_registry_count(a->fx) : 0u;
    afx_plugins *plugins = afx_app_plugins(a);
    for (uint32_t i = 0; i < n; i++) {
        const fx_effect *fx = fx_registry_at(a->fx, i);
        bool adj = strncmp(fx->menu, "Adjustments/", 12) == 0;
        const afx_plugin_info *info = afx_plugins_info(plugins, fx);
        char id[200], label[160], name[128], tip[700];
        app_cmd_def d;
        if (!adj && !afx_is_effect(fx)) continue;
        if (fx->flags & FX_FLAG_MASK_ONLY) continue;        /* selection effects: no v1 menu */
        snprintf(id, sizeof id, "%s.%s", adj ? "adjust" : "effects", fx->id);
        if (app_cmd_exists(a, id)) continue;
        afx_effect_name(fx, name, sizeof name);
        snprintf(label, sizeof label, "%s%s", name, (fx->flags & FX_FLAG_NO_DIALOG) ? "" : "...");
        memset(&d, 0, sizeof d);
        d.id = id;
        d.label = label;
        d.icon = adj ? UI_ICON_ADJUSTMENTS : UI_ICON_EFFECTS;
        if (info) {
            /* plugin effects: own icon and a tooltip with author and file (D EffectsMenu) */
            d.icon = UI_ICON_WIN_TOOLS;
            snprintf(tip, sizeof tip, "%s%s%s%s%s - %s", name, info->author[0] ? " by " : "",
                     info->author, info->version[0] ? ", version " : "", info->version,
                     info->path);
            d.tip = tip;
        }
        d.flags = APP_CMD_NEEDS_DOC;
        d.run = cmd_effect;
        d.ud = (void *)(uintptr_t)fx;
        (void)app_cmd_register(a, &d);
    }
}

int afx_app_load_plugins(app *a, const char *dir)
{
    afx_plugins *p = afx_app_plugins(a);
    int n;
    if (!p) {
        p = afx_plugins_create();
        if (!p) return 0;
        afx_app_set_plugins(a, p);
        p = afx_app_plugins(a);
        if (!p) return 0;
    }
    n = afx_plugins_scan(p, a->fx, dir);
    afx_register_commands(a);
    return n;
}

static void load_plugins(app *a)
{
    char path[1100];
    const char *data = pal_dir(PAL_DIR_DATA), *exe = pal_dir(PAL_DIR_EXE);
    afx_plugins *p = afx_plugins_create();
    int n = 0;
    if (!p || !a->fx) {
        afx_plugins_destroy(p);
        return;
    }
    afx_app_set_plugins(a, p);
    if (!afx_app_plugins(a)) return;
    /* config_dir "" means "no user files at all" (tests, scripted runs) */
    if (data && *data && !(a->opts.config_dir && !*a->opts.config_dir)) {
        pal_path_join(path, sizeof path, data, "plugins");
        n += afx_plugins_scan(p, a->fx, path);
    }
    if (exe && *exe) {
        pal_path_join(path, sizeof path, exe, "plugins");
        n += afx_plugins_scan(p, a->fx, path);
    }
    if (n > 0 || afx_plugins_error_count(p) > 0u)
        pal_log(PAL_LOG_INFO, "effects: %d from plugins (%u files), %u plugin errors", n,
                (unsigned)afx_plugins_lib_count(p), (unsigned)afx_plugins_error_count(p));
}

void mod_effects(app *a)
{
    app_cmd_def d;
    afx_widgets_register(a);
    if (!a->opts.disable_plugins) load_plugins(a);
    afx_register_commands(a);
    memset(&d, 0, sizeof d);
    d.id = "effects.repeat";
    d.label = "Repeat";
    d.icon = UI_ICON_EFFECTS;
    d.flags = APP_CMD_NEEDS_DOC;
    d.run = cmd_repeat;
    d.enabled = can_repeat;
    (void)app_cmd_register(a, &d);
    memset(&d, 0, sizeof d);
    d.id = "effects.plugin_errors";
    d.label = "Plugin Errors...";
    d.icon = UI_ICON_WARNING;
    d.run = cmd_plugin_errors;
    d.enabled = has_plugin_errors;
    (void)app_cmd_register(a, &d);
}
