#!/usr/bin/env python3
"""Generate the paint.c application icon (an original design, lane I).

The mark is ".c": a white pixel dot followed by a thick letter c whose
stroke runs through the color wheel, on a dark blue rounded tile. Nothing
in it is taken from Paint.NET's artwork (P-02, X-02).

Outputs (all committed, so builds never need this script):
  assets/icons/paintc.svg            scalable source (hicolor scalable)
  assets/icons/paintc-small.svg      variant with heavier strokes for <= 32 px
  assets/icons/png/paintc-<N>.png    N = 16 24 32 48 64 128 256 512 1024
  assets/icons/paintc.ico            Windows icon (PNG entries 16..256)
  assets/icons/paintc.icns           macOS icon (PNG entries, own encoder)
  src/app/io/icon_data.c             32, 64 and 256 px PNGs as C arrays
                                     (the window icon, app_icon_rgba)

Requires python3 and rsvg-convert (librsvg). Usage, from the repository
root:  python3 packaging/icons/make_icons.py
"""
import colorsys
import math
import os
import struct
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "assets", "icons")
SIZES = [16, 24, 32, 48, 64, 128, 256, 512, 1024]
ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]
EMBED_SIZES = [32, 64, 256]


def hexcol(h, s, v):
    r, g, b = colorsys.hsv_to_rgb(h % 1.0, s, v)
    return "#%02X%02X%02X" % (round(r * 255), round(g * 255), round(b * 255))


def svg(small):
    """The icon on a 1024 x 1024 canvas. small: heavier strokes for tiny sizes."""
    cx, cy = 600.0, 512.0
    ring_r = 214.0 if small else 220.0
    ring_w = 176.0 if small else 140.0
    # the gap of the c faces right: the stroke runs from a0 to a1 (degrees,
    # 0 = +x, counter-clockwise on screen means negative y)
    a0, a1 = 48.0, 312.0
    segs = 96
    hue0, hue_span = 0.97, 0.65      # red, orange, yellow, green, cyan, blue
    parts = []
    parts.append('<?xml version="1.0" encoding="UTF-8"?>')
    parts.append('<!-- paint.c application icon (original design). Generated by '
                 'packaging/icons/make_icons.py; edit the script, not this file. -->')
    parts.append('<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" '
                 'viewBox="0 0 1024 1024">')
    parts.append('<defs><linearGradient id="tile" x1="0" y1="0" x2="0" y2="1">'
                 '<stop offset="0" stop-color="#2E3F73"/>'
                 '<stop offset="1" stop-color="#121931"/></linearGradient>'
                 '<linearGradient id="gloss" x1="0" y1="0" x2="0" y2="1">'
                 '<stop offset="0" stop-color="#FFFFFF" stop-opacity="0.10"/>'
                 '<stop offset="0.5" stop-color="#FFFFFF" stop-opacity="0"/></linearGradient>'
                 '</defs>')
    pad = 40 if small else 64
    rad = 180 if small else 200
    size = 1024 - 2 * pad
    parts.append('<rect x="%d" y="%d" width="%d" height="%d" rx="%d" fill="url(#tile)"/>'
                 % (pad, pad, size, size, rad))
    parts.append('<rect x="%d" y="%d" width="%d" height="%d" rx="%d" fill="url(#gloss)"/>'
                 % (pad, pad, size, size, rad))
    if not small:
        parts.append('<rect x="%d" y="%d" width="%d" height="%d" rx="%d" fill="none" '
                     'stroke="#FFFFFF" stroke-opacity="0.12" stroke-width="6"/>'
                     % (pad + 3, pad + 3, size - 6, size - 6, rad - 3))
    # the c: annular sectors through the hues (a conic gradient that every
    # SVG renderer draws the same), overlapping slightly to hide seams
    r_in, r_out = ring_r - ring_w / 2, ring_r + ring_w / 2

    def pt(r, deg):
        t = math.radians(deg)
        return cx + r * math.cos(t), cy - r * math.sin(t)

    for i in range(segs):
        t0 = i / segs
        t1 = (i + 1) / segs
        d0 = a0 + (a1 - a0) * t0
        d1 = a0 + (a1 - a0) * min(1.0, t1 + 0.004)
        col = hexcol(hue0 + hue_span * (t0 + t1) / 2, 0.78, 1.0)
        x0, y0 = pt(r_out, d0)
        x1, y1 = pt(r_out, d1)
        x2, y2 = pt(r_in, d1)
        x3, y3 = pt(r_in, d0)
        parts.append('<path fill="%s" d="M%.2f %.2fA%.2f %.2f 0 0 0 %.2f %.2fL%.2f %.2f'
                     'A%.2f %.2f 0 0 1 %.2f %.2fZ"/>'
                     % (col, x0, y0, r_out, r_out, x1, y1, x2, y2, r_in, r_in, x3, y3))
    # round caps in the end colors
    for deg, t in ((a0, 0.0), (a1, 1.0)):
        x, y = pt(ring_r, deg)
        col = hexcol(hue0 + hue_span * t, 0.78, 1.0)
        parts.append('<circle cx="%.2f" cy="%.2f" r="%.2f" fill="%s"/>' % (x, y, ring_w / 2, col))
    # the dot: one pixel, bottom aligned with the c
    dot = 170.0 if small else 140.0
    dx = 118.0 if small else 150.0
    dy = cy + r_out - dot
    parts.append('<rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" rx="%.2f" fill="#F5F7FC"/>'
                 % (dx, dy, dot, dot, dot * 0.2))
    parts.append('</svg>')
    return "\n".join(parts) + "\n"


def render(svg_path, size, out):
    subprocess.check_call(["rsvg-convert", "-w", str(size), "-h", str(size), "-o", out,
                           svg_path])


def ico(pngs, out):
    """ICO with PNG entries (Windows Vista and later read them at every size)."""
    data = [open(p, "rb").read() for _, p in pngs]
    head = struct.pack("<HHH", 0, 1, len(pngs))
    off = 6 + 16 * len(pngs)
    dirs = b""
    for (size, _), d in zip(pngs, data):
        b = 0 if size >= 256 else size
        dirs += struct.pack("<BBBBHHII", b, b, 0, 0, 1, 32, len(d), off)
        off += len(d)
    with open(out, "wb") as f:
        f.write(head + dirs + b"".join(data))


def icns(pngs, out):
    """ICNS with PNG payloads: icp4 16, icp5 32, icp6 64, ic07 128, ic08 256,
    ic09 512, ic10 1024 (512@2x), ic11 32 (16@2x), ic12 64 (32@2x),
    ic13 256 (128@2x), ic14 512 (256@2x)."""
    by = dict(pngs)
    types = [("icp4", 16), ("icp5", 32), ("icp6", 64), ("ic07", 128), ("ic08", 256),
             ("ic09", 512), ("ic10", 1024), ("ic11", 32), ("ic12", 64), ("ic13", 256),
             ("ic14", 512)]
    body = b""
    for t, s in types:
        d = open(by[s], "rb").read()
        body += t.encode("ascii") + struct.pack(">I", 8 + len(d)) + d
    with open(out, "wb") as f:
        f.write(b"icns" + struct.pack(">I", 8 + len(body)) + body)


def c_array(pngs, out):
    lines = ["/* icon_data.c - the paint.c icon as PNG files for the window icon",
             " * (app_icon_rgba). Generated by packaging/icons/make_icons.py from",
             " * assets/icons; do not edit. The design is original to paint.c. */",
             "#include <stddef.h>", ""]
    names = []
    for size, path in pngs:
        d = open(path, "rb").read()
        name = "io_icon_png_%d" % size
        names.append((size, name, len(d)))
        lines.append("extern const unsigned char %s[];" % name)
        lines.append("const unsigned char %s[%d] = {" % (name, len(d)))
        for i in range(0, len(d), 16):
            lines.append("    " + ", ".join("0x%02x" % b for b in d[i:i + 16]) + ",")
        lines.append("};")
        lines.append("")
    lines.append("extern const unsigned char *const io_icon_pngs[%d];" % len(names))
    lines.append("extern const size_t io_icon_png_sizes[%d];" % len(names))
    lines.append("extern const int io_icon_png_dims[%d];" % len(names))
    lines.append("const unsigned char *const io_icon_pngs[%d] = { %s };"
                 % (len(names), ", ".join(n for _, n, _ in names)))
    lines.append("const size_t io_icon_png_sizes[%d] = { %s };"
                 % (len(names), ", ".join("%du" % l for _, _, l in names)))
    lines.append("const int io_icon_png_dims[%d] = { %s };"
                 % (len(names), ", ".join(str(s) for s, _, _ in names)))
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    os.makedirs(os.path.join(OUT, "png"), exist_ok=True)
    big = os.path.join(OUT, "paintc.svg")
    small = os.path.join(OUT, "paintc-small.svg")
    with open(big, "w") as f:
        f.write(svg(False))
    with open(small, "w") as f:
        f.write(svg(True))
    pngs = []
    for s in SIZES:
        p = os.path.join(OUT, "png", "paintc-%d.png" % s)
        render(small if s <= 32 else big, s, p)
        pngs.append((s, p))
    ico([(s, p) for s, p in pngs if s in ICO_SIZES], os.path.join(OUT, "paintc.ico"))
    icns(pngs, os.path.join(OUT, "paintc.icns"))
    c_array([(s, p) for s, p in pngs if s in EMBED_SIZES],
            os.path.join(ROOT, "src", "app", "io", "icon_data.c"))
    print("icons written to", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
