# PcEmbed.cmake - turn binary files into C byte arrays at build time (lane L3).
#
# Module use (from a CMakeLists.txt after include(PcEmbed)):
#   pc_embed_file(<out-var> <input> <symbol>)
# appends the path of a generated .c file to <out-var>. The file defines
#   const unsigned char <symbol>[];      (the bytes, plus one NUL guard byte)
#   const size_t        <symbol>_size;   (the byte count without the guard)
# and is regenerated whenever the input or this script changes.
#
# Script use (internal, run by the custom command):
#   cmake -DPC_EMBED_IN=<file> -DPC_EMBED_OUT=<file.c> -DPC_EMBED_SYM=<name>
#         -P PcEmbed.cmake

if(CMAKE_SCRIPT_MODE_FILE AND DEFINED PC_EMBED_IN)
  file(READ "${PC_EMBED_IN}" _hex HEX)
  string(LENGTH "${_hex}" _n)
  math(EXPR _bytes "${_n} / 2")
  # 16 bytes (32 hex digits) per line, then 0xNN, per byte.
  set(_h16 "[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]")
  string(REGEX REPLACE "(${_h16}${_h16}${_h16}${_h16})" "\\1\n" _hex "${_hex}")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _hex "${_hex}")
  get_filename_component(_name "${PC_EMBED_IN}" NAME)
  file(WRITE "${PC_EMBED_OUT}.tmp"
    "/* Generated by cmake/PcEmbed.cmake from ${_name}. Do not edit. */\n"
    "#include <stddef.h>\n"
    "extern const unsigned char ${PC_EMBED_SYM}[];\n"
    "extern const size_t ${PC_EMBED_SYM}_size;\n"
    "const size_t ${PC_EMBED_SYM}_size = ${_bytes}u;\n"
    "const unsigned char ${PC_EMBED_SYM}[${_bytes} + 1] = {\n"
    "${_hex}\n0x00\n};\n")
  file(RENAME "${PC_EMBED_OUT}.tmp" "${PC_EMBED_OUT}")
  return()
endif()

set(PC_EMBED_SCRIPT "${CMAKE_CURRENT_LIST_FILE}")

function(pc_embed_file out_var input symbol)
  set(_out "${CMAKE_CURRENT_BINARY_DIR}/embed/${symbol}.c")
  add_custom_command(
    OUTPUT "${_out}"
    COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/embed"
    COMMAND ${CMAKE_COMMAND} -DPC_EMBED_IN=${input} -DPC_EMBED_OUT=${_out}
            -DPC_EMBED_SYM=${symbol} -P "${PC_EMBED_SCRIPT}"
    DEPENDS "${input}" "${PC_EMBED_SCRIPT}"
    COMMENT "Embedding ${symbol}"
    VERBATIM)
  set(${out_var} ${${out_var}} "${_out}" PARENT_SCOPE)
endfunction()
